instance_create_depth(x,y,depth,obj_enemy_mkm_body)
instance_create_depth(x,y,depth-1,obj_enemy_mkm_cloak)
instance_create_depth(x-2,y+13,depth+1,obj_enemy_mkm_l_leg_0)
instance_create_depth(x+2,y+13,depth+1,obj_enemy_mkm_r_leg_0)
instance_create_depth(x-6,y+21,depth,obj_enemy_mkm_l_leg_1)
instance_create_depth(x+6,y+21,depth,obj_enemy_mkm_r_leg_1)
instance_create_depth(x,y-13,depth-3,obj_enemy_mkm_head)
instance_create_depth(x-9,y-4,depth-3,obj_enemy_mkm_l_hand_piece_0)
instance_create_depth(x+8,y-4,depth - 3,obj_enemy_mkm_r_hand_piece_0)
instance_create_depth(x-14,y+2,depth - 4,obj_enemy_mkm_l_hand_piece_1)
instance_create_depth(x+13,y+2,depth - 4,obj_enemy_mkm_r_hand_piece_1)
instance_create_depth(x-19,y+8,depth-5,obj_enemy_mkm_l_hand_piece_2)
instance_create_depth(x+18,y+8,depth-5,obj_enemy_mkm_r_hand_piece_2)
instance_create_depth(x-24,y+14,depth-6,obj_enemy_mkm_l_hand)
instance_create_depth(x+23,y+14,depth-6,obj_enemy_mkm_r_hand)
timer = 0
hand_check = 0
