draw_self()
draw_set_halign(fa_left)
draw_set_color(c_white)
draw_text(x+17,y+10,"HP: ")
draw_set_halign(fa_right)
draw_text(x+72,y+10,string(global.stev_array[0]) + "/" + string(global.stev_array[1]))
draw_set_halign(fa_left)
draw_text(x+17,y+2,"Steve")
draw_sprite(spr_steve_p_small,0,x+4,y+5)
